### ISSUE TITLE
Investigate potential changes to our data structure

### ISSUE THREAD

**Issue by space333k** [AlgoETS/BullETS#72] opened 2021-09-08 16:53 UTC
We need to check if changing data structure again is worth it.

**Comment by SamiMammouche** [comment] 2022-01-30 19:40
We should investigate and have a discussion to see if we should be using pandas for storing data. We also should reconsider if our current data structure is easy to understand and allows to quickly retrieve data for strategies.

**Comment by SamiMammouche** [comment] 2022-03-06 18:23
Duplicate of #110

**Closed as completed** 2022-03-06 18:23 UTC
Labels: question, important
